spring:
  application:
    name: Oauth2 Resource Server Example
server:
  port: 8080
security:
  oauth2:
    resource:
      id: test-autorisation-api
      jwt:
        token-uri: https://<server>/oauth/token
        key-set-uri: https://<server>/oauth/token_keys
        #key-uri: https://<server>/oauth/token_key
management:
  endpoint.health.cache.time-to-live: 15000 # 15 seconds cache
  endpoints:
    web:
      exposure.include: "*" # autorized web endpoints list
logging:
  level:
    org.springframework:
      security: debug
      security.oauth2: debug
  pattern:
    console: '${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40class{36}.%M %L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
